#!/bin/sh
set -e

if [ -z "$1" ]; then
    echo "Error: Backup name missing"
    echo "Please specify a backup name, e.g., 'restore 20141104'"
    echo "Finished: FAILURE"
    exit 1
fi

for var in MYSQL_ENV_MYSQL_HOST MYSQL_ENV_MYSQL_USER MYSQL_ENV_MYSQL_DATABASE MYSQL_ENV_MYSQL_PASSWORD; do
    if [ -z "$(eval echo \$$var)" ]; then
        echo "Error: $var not set"
        echo "Finished: FAILURE"
        exit 1
    fi
done

if ! echo "$1" | grep -Eq '^[a-zA-Z0-9_-]+$'; then
    echo "The given backup name does not match the expected pattern: only characters, digits, underscore, and dash are allowed ([a-zA-Z0-9_-])."
    echo "Finished: FAILURE"
    exit 1
fi

FILES_ARCHIVE="/backups/backup_$1.tar.gz"
SQL_ARCHIVE="/backups/backup_$1.sql.bz2"

if [ ! -f "${FILES_ARCHIVE}" ]; then
    echo "The file $FILES_ARCHIVE does not exist. Aborting."
    echo "Finished: FAILURE."
    exit 1
fi

if [ ! -f "${SQL_ARCHIVE}" ]; then
    echo "The file $SQL_ARCHIVE does not exist. Aborting."
    echo "Finished: FAILURE."
    exit 1
fi

echo "Deleting files from /var/www/html/"
rm -rf /var/www/html/*

echo "Restoring files from $FILES_ARCHIVE to /var/www/html"
pigz -dc "${FILES_ARCHIVE}" | tar -xzf - --directory="/var/www/html/"

WP_CONFIG="/var/www/html/wp-config.php"
sed -i -e "s/define('DB_NAME', '.*');/define('DB_NAME', '$MYSQL_ENV_MYSQL_DATABASE');/" \
       -e "s/define('DB_USER', '.*');/define('DB_USER', '$MYSQL_ENV_MYSQL_USER');/" \
       -e "s/define('DB_PASSWORD', '.*');/define('DB_PASSWORD', '$MYSQL_ENV_MYSQL_PASSWORD');/" \
       -e "s/define('DB_HOST', '.*');/define('DB_HOST', '$MYSQL_ENV_MYSQL_HOST:$MYSQL_PORT_3306_TCP_PORT');/" \
       "$WP_CONFIG"

chown -R www-data:www-data /var/www/html

echo "Restoring data from MySQL dump file $SQL_ARCHIVE"
bunzip2 < "${SQL_ARCHIVE}" | mysql --host="$MYSQL_ENV_MYSQL_HOST" --user="$MYSQL_ENV_MYSQL_USER" --password="$MYSQL_ENV_MYSQL_PASSWORD" "$MYSQL_ENV_MYSQL_DATABASE"

echo 'Finished: SUCCESS'
